import type { ReportItem, TemplateDef } from './types';

export const INITIAL_TEMPLATES: TemplateDef[] = [
  {
    id: 'gp',
    name: 'General Physical',
    nameHe: 'בדיקה גופנית כללית',
    short: 'GP',
    shortHe: 'כל',
    accent: '#F2B23A',
    soft: '#FCEAC6',
    cats: [
      {
        name: 'General Appearance',
        nameHe: 'מראה כללי',
        type: 'Free text',
        sample: 'Alert, well-nourished, no acute distress',
        sampleHe: 'ערני, מוזן היטב, ללא מצוקה חריפה',
      },
      { name: 'Temperature', nameHe: 'חום', type: 'Number', sample: '37.2 °C', sampleHe: '37.2 °C' },
      { name: 'Heart Rate', nameHe: 'דופק', type: 'Number', sample: '78 bpm', sampleHe: '78 פעימות/דק׳' },
      {
        name: 'Blood Pressure',
        nameHe: 'לחץ דם',
        type: 'Free text',
        sample: '122/78 mmHg',
        sampleHe: '122/78 mmHg',
        low: true,
      },
      {
        name: 'Lungs',
        nameHe: 'ריאות',
        type: 'List',
        options: ['Clear', 'Wheeze', 'Crackles'],
        optionsHe: ['נקיות', 'צפצופים', 'חרחורים'],
        sample: 'Clear bilaterally',
        sampleHe: 'נקיות דו-צדדית',
      },
      {
        name: 'Skin',
        nameHe: 'עור',
        type: 'Free text',
        sample: 'Warm and dry, no rash',
        sampleHe: 'חמים ויבש, ללא פריחה',
        low: true,
      },
      {
        name: 'Notes',
        nameHe: 'הערות',
        type: 'Free text',
        sample: 'Reports mild fatigue past week',
        sampleHe: 'מדווח על עייפות קלה בשבוע האחרון',
      },
    ],
  },
  {
    id: 'cardio',
    name: 'Cardiac Exam',
    nameHe: 'בדיקת לב',
    short: 'CV',
    shortHe: 'לב',
    accent: '#8FB6A6',
    soft: '#DDEAE3',
    cats: [
      { name: 'General Appearance', nameHe: 'מראה כללי', type: 'Free text', sample: 'Comfortable at rest', sampleHe: 'נינוח במנוחה' },
      { name: 'Heart Sounds', nameHe: 'קולות לב', type: 'Free text', sample: 'S1 S2 normal, no murmur', sampleHe: 'S1 S2 תקינים, ללא אוושה' },
      {
        name: 'Rhythm',
        nameHe: 'קצב',
        type: 'List',
        options: ['Regular', 'Irregular'],
        optionsHe: ['סדיר', 'לא סדיר'],
        sample: 'Regular',
        sampleHe: 'סדיר',
      },
      { name: 'Heart Rate', nameHe: 'דופק', type: 'Number', sample: '72 bpm', sampleHe: '72 פעימות/דק׳' },
      {
        name: 'Blood Pressure',
        nameHe: 'לחץ דם',
        type: 'Free text',
        sample: '128/82 mmHg',
        sampleHe: '128/82 mmHg',
        low: true,
      },
      { name: 'Peripheral Pulses', nameHe: 'דפקים היקפיים', type: 'Free text', sample: 'Symmetric, 2+', sampleHe: 'סימטריים, 2+' },
      {
        name: 'Edema',
        nameHe: 'בצקת',
        type: 'List',
        options: ['None', 'Mild', 'Marked'],
        optionsHe: ['ללא', 'קלה', 'ניכרת'],
        sample: 'None',
        sampleHe: 'ללא',
      },
    ],
  },
  {
    id: 'derm',
    name: 'Dermatology',
    nameHe: 'דרמטולוגיה',
    short: 'Dx',
    shortHe: 'עו',
    accent: '#0E9A82',
    soft: '#D2EDE6',
    cats: [
      {
        name: 'Lesion Site',
        nameHe: 'מיקום הנגע',
        type: 'Free text',
        sample: 'Left forearm, dorsal',
        sampleHe: 'אמה שמאל, גבי',
        low: true,
      },
      { name: 'Size', nameHe: 'גודל', type: 'Number', sample: '12 mm', sampleHe: '12 מ״מ' },
      { name: 'Color', nameHe: 'צבע', type: 'Free text', sample: 'Erythematous', sampleHe: 'אדמומי' },
      {
        name: 'Border',
        nameHe: 'גבול',
        type: 'List',
        options: ['Well-defined', 'Irregular'],
        optionsHe: ['מוגדר היטב', 'לא סדיר'],
        sample: 'Well-defined',
        sampleHe: 'מוגדר היטב',
      },
      { name: 'Texture', nameHe: 'מרקם', type: 'Free text', sample: 'Slightly raised, scaly', sampleHe: 'מעט מורם, קשקשי' },
      { name: 'Notes', nameHe: 'הערות', type: 'Free text', sample: 'No bleeding or ulceration', sampleHe: 'ללא דימום או כיב' },
    ],
  },
  {
    id: 'peds',
    name: 'Pediatric Check',
    nameHe: 'בדיקת ילדים',
    short: 'Pd',
    shortHe: 'יל',
    accent: '#E08A56',
    soft: '#F7E0D2',
    cats: [
      {
        name: 'General Appearance',
        nameHe: 'מראה כללי',
        type: 'Free text',
        sample: 'Active, playful, well-hydrated',
        sampleHe: 'פעיל, משחקי, רווי היטב',
      },
      { name: 'Weight', nameHe: 'משקל', type: 'Number', sample: '14.2 kg', sampleHe: '14.2 ק״ג' },
      { name: 'Temperature', nameHe: 'חום', type: 'Number', sample: '36.9 °C', sampleHe: '36.9 °C' },
      {
        name: 'Ears',
        nameHe: 'אוזניים',
        type: 'List',
        options: ['Normal', 'Red', 'Fluid'],
        optionsHe: ['תקינות', 'אדומות', 'נוזל'],
        sample: 'Normal',
        sampleHe: 'תקינות',
      },
      { name: 'Throat', nameHe: 'גרון', type: 'Free text', sample: 'No erythema', sampleHe: 'ללא אדמומיות', low: true },
      { name: 'Notes', nameHe: 'הערות', type: 'Free text', sample: 'Immunizations up to date', sampleHe: 'חיסונים מעודכנים' },
    ],
  },
];

export const INITIAL_REPORTS: ReportItem[] = [
  { id: 'r1', date: 'Jun 28, 2026', time: '09:14', template: 'General Physical' },
  { id: 'r2', date: 'Jun 27, 2026', time: '16:42', template: 'Cardiac Exam' },
  { id: 'r3', date: 'Jun 27, 2026', time: '11:05', template: 'Pediatric Check' },
  { id: 'r4', date: 'Jun 26, 2026', time: '14:20', template: 'Dermatology' },
  { id: 'r5', date: 'Jun 25, 2026', time: '08:50', template: 'General Physical' },
  { id: 'r6', date: 'Jun 24, 2026', time: '15:33', template: 'Cardiac Exam' },
];
