import type { TemplateDef } from './types';

export const INITIAL_TEMPLATES: TemplateDef[] = [
  {
    id: 'gp',
    name: 'General Physical',
    nameHe: 'בדיקה גופנית כללית',
    short: 'GP',
    shortHe: 'כל',
    accent: '#F2B23A',
    soft: '#FCEAC6',
    cats: [
      {
        name: 'General Appearance',
        nameHe: 'מראה כללי',
        aliases: ['appearance', 'general appearance', 'מראה', 'מצב כללי'],
        type: 'Free text',
        sample: 'Alert, well-nourished, no acute distress',
        sampleHe: 'ערני, מוזן היטב, ללא מצוקה חריפה',
      },
      { name: 'Temperature', nameHe: 'חום', aliases: ['temp', 'temperature', 'טמפרטורה'], type: 'Number', sample: '37.2 °C', sampleHe: '37.2 °C' },
      { name: 'Heart Rate', nameHe: 'דופק', aliases: ['pulse', 'heartrate', 'קצב לב'], type: 'Number', sample: '78 bpm', sampleHe: '78 פעימות/דק׳' },
      {
        name: 'Blood Pressure',
        nameHe: 'לחץ דם',
        aliases: ['bp', 'pressure', 'לחץ'],
        type: 'Free text',
        sample: '122/78 mmHg',
        sampleHe: '122/78 mmHg',
        low: true,
      },
      {
        name: 'Lungs',
        nameHe: 'ריאות',
        aliases: ['lungs', 'chest', 'breath sounds', 'חזה', 'נשימות'],
        type: 'List',
        options: ['Clear', 'Wheeze', 'Crackles'],
        optionsHe: ['נקיות', 'צפצופים', 'חרחורים'],
        sample: 'Clear bilaterally',
        sampleHe: 'נקיות דו-צדדית',
      },
      {
        name: 'Skin',
        nameHe: 'עור',
        aliases: ['skin', 'derm', 'העור'],
        type: 'Free text',
        sample: 'Warm and dry, no rash',
        sampleHe: 'חמים ויבש, ללא פריחה',
        low: true,
      },
      {
        name: 'Notes',
        nameHe: 'הערות',
        aliases: ['note', 'comments', 'הערה'],
        type: 'Free text',
        sample: 'Reports mild fatigue past week',
        sampleHe: 'מדווח על עייפות קלה בשבוע האחרון',
      },
    ],
  },
];
